# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_varCPP <- function(x, mu) {
    .Call('_diem_fast_varCPP', PACKAGE = 'diem', x, mu)
}

