# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LlkDirMultSparse <- function(x, sizes, alpha, debug = FALSE) {
    .Call('_diem_LlkDirMultSparse', PACKAGE = 'diem', x, sizes, alpha, debug)
}

compute_step <- function(x, sizes, weights, alpha, tol = 100L, debug = FALSE) {
    .Call('_diem_compute_step', PACKAGE = 'diem', x, sizes, weights, alpha, tol, debug)
}

compute_LOO_step <- function(x, sizes, weights, alpha, tol = 100L, debug = FALSE) {
    .Call('_diem_compute_LOO_step', PACKAGE = 'diem', x, sizes, weights, alpha, tol, debug)
}

compute_fp_step <- function(x, sizes, weights, alpha, tol = 100L, debug = FALSE) {
    .Call('_diem_compute_fp_step', PACKAGE = 'diem', x, sizes, weights, alpha, tol, debug)
}

fast_varCPP <- function(x, mu) {
    .Call('_diem_fast_varCPP', PACKAGE = 'diem', x, mu)
}

