# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvn_logllk_diagCPP <- function(x, mu, sgma) {
    .Call('_diem_mvn_logllk_diagCPP', PACKAGE = 'diem', x, mu, sgma)
}

fraction_logCPP <- function(x) {
    .Call('_diem_fraction_logCPP', PACKAGE = 'diem', x)
}

sum_logCPP <- function(x) {
    .Call('_diem_sum_logCPP', PACKAGE = 'diem', x)
}

e_stepCPP <- function(x, k, mu, sgma, tau, semisup = FALSE, labels = NULL) {
    .Call('_diem_e_stepCPP', PACKAGE = 'diem', x, k, mu, sgma, tau, semisup, labels)
}

get_llkCPP <- function(x, mu, sgma, tau, semisup = FALSE, labels = NULL) {
    .Call('_diem_get_llkCPP', PACKAGE = 'diem', x, mu, sgma, tau, semisup, labels)
}

fast_varCPP <- function(x, mu) {
    .Call('_diem_fast_varCPP', PACKAGE = 'diem', x, mu)
}

fast_row_scaleCPP <- function(x, mu, sigma_sq) {
    .Call('_diem_fast_row_scaleCPP', PACKAGE = 'diem', x, mu, sigma_sq)
}

